### ISSUE TITLE
Start Up Error

### ISSUE THREAD

**Issue by 0lIvIa09** [ail-project/lacus#21] opened 2024-08-14 07:40 UTC
When I run `poetry run start` from the lacus directory I get the error below. Any ideas on how I fix this? I've had Lacus working for a few months now but recently it won't start up.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/lacus/bin/update.py", line 13, in <module>
    from lacus.default import get_homedir, get_config
  File "/lacus/lacus/__init__.py", line 1, in <module>
    from .lacus import Lacus
  File "/lacus/lacus/lacus.py", line 12, in <module>
    from lacuscore import LacusCore, LacusCoreMonitoring
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/lacuscore/__init__.py", line 1, in <module>
    from .lacuscore import LacusCore
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/lacuscore/lacuscore.py", line 30, in <module>
    from playwrightcapture import Capture, PlaywrightCaptureException, InvalidPlaywrightParameter
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/playwrightcapture/__init__.py", line 1, in <module>
    from .capture import Capture  # noqa
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/playwrightcapture/capture.py", line 25, in <module>
    import dateparser
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/dateparser/__init__.py", line 3, in <module>
    from .conf import apply_settings
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/dateparser/conf.py", line 7, in <module>
    from .parser import date_order_chart
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/dateparser/parser.py", line 9, in <module>
    from dateparser.utils import (
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/dateparser/utils/__init__.py", line 12, in <module>
    from dateparser.timezone_parser import StaticTzInfo, _tz_offsets
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/dateparser/timezone_parser.py", line 89, in <module>
    _tz_offsets = list(build_tz_offsets(_search_regex_parts))
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/dateparser/timezone_parser.py", line 73, in build_tz_offsets
    yield get_offset(tz_obj, regex)
  File "/root/.cache/pypoetry/virtualenvs/lacus-RNxvEGfM-py3.10/lib/python3.10/site-packages/dateparser/timezone_parser.py", line 62, in get_offset
    "regex": re.compile(
AttributeError: module 'regex' has no attribute 'compile'
```

**Comment by Rafiot** [comment] 2024-08-14 08:12
The paths in the stack trace are extremely odd. It looks like you cloned the repository directly in `/` on your machine and the virtualenv in your `/root/` home directory?

Are you trying to run the project as root? Or with sudo? I think that the issue is related to the virtual environment not loading properly. This project should never be run as root / with sudo.

If I'm right, my recommandation is to re-install as a non-root user, this should work. And if I'm not right, I'll need to see the step-by-step of the installation because I cannot reproduce the issue on a fresh install myself.

**Comment by 0lIvIa09** [comment] 2024-08-14 08:41
I'm trying to re-install it under a non-root user and I'm getting the issue below when I run `poetry install` from the lacus directory.

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]

**Comment by Rafiot** [comment] 2024-08-14 08:53
That's another issue, I think. Did you install poetry with apt? This is going to give you a super old version that doesn't supports required features.

As described in the [install guide](https://github.com/ail-project/lacus?tab=readme-ov-file#system-dependencies), please follow the official poetry installation procedure: https://python-poetry.org/docs/#installation

**Comment by 0lIvIa09** [comment] 2024-08-14 09:14
Thank you for your help. All seems to be working now.

**Comment by Rafiot** [comment] 2024-08-14 09:18
Great! I'm closing this issue, feel free to open a new one if needed.

**Closed by Rafiot** 2024-08-14 09:18 UTC
